---
language: python
python: "2.7"
cache: pip

sudo: true

addons:
  apt:
    packages:
    - python-pip

install:
  - "pip install ansible"
  - "ansible --version"
  - "sudo apt-get install -y zsh"

script:
  - ansible-playbook shell.yml -i testInventory.yml
