---
language: python
python: "2.7"
cache: pip

sudo: true

addons:
  apt:
    packages:
    - python-pip

install:
  - pip install ansible
  - ansible --version
  - sudo echo /usr/bin/zsh >> /etc/shells

script:
  - ansible-playbook shell.yml -i testInventory.yml
