---
- name: install kvm related packages
  package:
    name: "{{ item }}"
    state: latest
  with_items:
    - libvirt-python
    - libvirt-client
    - libvirt-daemon-driver-qemu
    - libvirt-daemon-kvm
  run_once: true

- name: ensure libvirtd
  service:
    name: libvirtd
    state: started
    enabled: yes

- name: "define vm {{ vmName }}{{ vmId }}"
  virt:
    name: "{{ vmName }}{{ vmId }}"
    command: define
    xml: "{{ lookup('template', 'vm.xml.j2') }}"

#- name: "start vm {{ vmName }}{{ vmId }}"
#  virt:
#    name: "{{ vmName }}{{ vmId }}"
#    state: running
