---
- name: prepare ssh pipelining
  copy:
    src: etc/sudoers.d/vagrant
    dest: /etc/sudoers.d/vagrant
    mode: 0644
    owner: root
    group: root

- name: ensure my ssh key
  authorized_key:
    user: vagrant
    state: present
    key: "{{ lookup('file', '/home/dano0b/.ssh/id_rsa.pub') }}"

- name: set timezone
  timezone:
    name: Europe/Berlin

- name: install cockpit
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - cockpit
