---
- name: add websocket js
  copy:
    src: ws.js
    dest: "{{ dockerBuildDir }}/ws.js"
    owner: root
    group: root
    mode: 0644

- name: copy nginxStatic dockerfile
  template:
    src: "{{ dockerFileNginxStatic }}"
    dest: "{{ dockerBuildDir }}/Dockerfile"
    owner: dano0b
    group: dano0b
    mode: 0640

- name: build nginxStatic server docker image
  docker_image:
    path: "{{ dockerBuildDir }}"
    name: "{{ dockerImageNameNginxStatic }}"
    state: present
    force: yes
    buildargs: "{{ dockerBuildArgs |default(omit) }}"
    tag: "{{ dockerImageTag |default('latest') }}"
    repository: "{{ dockerImageRepo |default(omit) }}"
    push: "{{ dockerImagePush |default('no') }}"
