---
- name: create dockerBuildDir
  file:
    path: "{{ dockerBuildDir }}"
    state: directory
    owner: dano0b
    group: dano0b
    mode: 0750
  tags:
    - always

- name: include buildMojo.yml
  include: buildMojo.yml
  tags:
    - buildMojo

- name: remove dockerBuildDir
  file:
    path: "{{ dockerBuildDir }}"
    state: absent
  tags:
    - always

- name: include service.yml
  include: service.yml
  tags:
    - service
