---
- name: install required packages
  package:
    name: "{{ item }}"
    state: present
  become: true
  with_items:
    - zsh
    - git
    - curl
    - socat

- name: include python related tasks
  include: python.yml
  tags:
    - python
    - pip
    - virtualenv

- name: include powerline related tasks
  include: powerline.yml
  tags:
    - powerline

- name: include zsh related tasks
  include: zsh.yml
  tags:
    - zsh
    - oh-my-zsh
