---
- name: include linux package tasks
  import_tasks: linux.yml
  tags:
    - package
    - zsh
  when:
    - ansible_distribution != "MacOSX"

- name: include mac package tasks
  import_tasks: MacOSX.yml
  tags:
    - package
    - zsh
  when:
    - ansible_distribution == "MacOSX"

- name: include python related tasks
  import_tasks: python.yml
  tags:
    - python
    - pip
    - virtualenv

- name: include powerline related tasks
  import_tasks: powerline.yml
  when:
    - ansible_distribution != "MacOSX"
  tags:
    - powerline

- name: include zsh related tasks
  import_tasks: zsh.yml
  tags:
    - zsh
    - oh-my-zsh
