---
- name: copy docker repo
  copy:
    src: etc/yum.repos.d/docker-ce.repo
    dest: /etc/yum.repos.d/docker.repo
    mode: 0640
    owner: root
    group: root

- name: install docker-ce
  package:
    name: docker-ce
    state: present

- name: copy docker systemd service unit file
  copy:
    src: etc/systemd/system/docker.service
    dest: /etc/systemd/system/docker.service
    mode: 0640
    owner: root
    group: root

- name: copy docker sysconfig file
  copy:
    src: etc/sysconfig/docker
    dest: /etc/sysconfig/docker
    mode: 0640
    owner: root
    group: root

- name: ensure docker service
  service:
    name: docker
    state: started

- name: include master.yml
  include: master.yml
  when: ansible_hostname == swarmMaster

- name: include worker.yml
  include: worker.yml
  when: ansible_hostname != swarmMaster
