---
dependency:
  name: galaxy
driver:
  name: docker
docker:
  containers:
    - name: common
      image: centos
      image_version: latest
      ansible_groups:
        - group1
verifier:
  name: testinfra
