---
- name: reboot nodes
  shell: sleep 2 && shutdown -r now "Ansible reboot"
  async: 1
  poll: 0
  ignore_errors: true
  listen: "reboot and wait"

- name: wait for server to come back
  local_action: wait_for
  args:
    host: "{{ ansible_eth0.ipv4.address }}"
    port: 2022
    state: started
    delay: 30
    timeout: 300
  become: false
  listen: "reboot and wait"
