---
dependency:
  name: galaxy
driver:
  name: vagrant
vagrant:
  platforms:
    - name: centos7
      box: centos/7
  providers:
    - name: libvirt
      type: libvirt
      options:
        memory: 512
        cpus: 1
        driver: kvm
        video_type: vga
  instances:
    - name: quassel
      ansible_groups:
        - group1
verifier:
  name: testinfra
