---
all:
  children:
    local:
      vars:
        ansible_connection: local
      hosts:
        localhost:
    webservers:
      vars:
        ansible_port: 2022
        ansible_host: www.linuxisfreak.in
        ansible_connection: ssh
        ansible_user: root
      hosts:
        linuxisfreak:
