---
- name: include centos packages
  include: centos.yml
  when:
    - ansible_distribution == "CentOS"
    - ansible_distribution_major_version == "7"

- name: include fedora packages
  include: fedora.yml
  when:
    - ansible_distribution == "Fedora"
    - ansible_distribution_major_version == "25"

- name: ensure group
  group:
    name: "{{ roleGroupName }}"
    state: present

- name: ensure user
  user:
    name: "{{ roleUserName }}"
    group: "{{ roleGroupName }}"
    state: present
    createhome: yes
    home: "{{ roleHomePath }}"
    shell: /bin/bash

- name: ensure vim folder
  file:
    state: directory
    owner: "{{ roleUserName }}"
    group: "{{ roleGroupName }}"
    path: "{{ item }}"
    mode: 0750
  with_items:
    - "{{ roleHomePath }}/.vim"
    - "{{ roleHomePath }}/.vim/bundle"
    - "{{ roleHomePath }}/.vim/autoload"

- name: copy vimrc and pathogen.vim
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.destPath }}"
    owner: "{{ roleUserName }}"
    group: "{{ roleGroupName }}"
    mode: "{{ item.destMode }}"
    backup: yes
  with_items:
    - { src: 'pathogen.vim', destPath: '{{ roleHomePath }}/.vim/autoload/', destMode: '0640' }
    - { src: '.vimrc', destPath: '{{ roleHomePath }}/', destMode: '0640' }

- name: checkout vim plugins
  git:
    repo: "https://github.com/{{ item.githubUser }}/{{ item.githubRepo }}.git"
    dest: "{{ roleHomePath }}/.vim/bundle/{{ item.githubRepo }}"
  with_items:
    - { githubUser: 'scrooloose' , githubRepo: 'nerdtree' }
    - { githubUser: 'majutsushi' , githubRepo: 'tagbar' }
    - { githubUser: 'chase' , githubRepo: 'vim-ansible-yaml' }
    - { githubUser: 'mitsuhiko' , githubRepo: 'vim-jinja' }
    - { githubUser: 'elzr' , githubRepo: 'vim-json' }
    - { githubUser: 'plasticboy' , githubRepo: 'vim-markdown' }
    - { githubUser: 'sukima' , githubRepo: 'xmledit' }
